### PR TITLE
Add cost and technology for RO nuclear thermal rockets added by #1720

### PR DESCRIPTION
**Pull request by Bornholio**
See RO https://github.com/KSP-RO/RealismOverhaul/pull/1720

### CODE REVIEW

**Comment by NathanKell** [comment]
@pap1723 does this go in the xls or should it get merged?

**Comment by pap1723** [comment]
I was working with this one today. I will be merging it later with XLS
integrations as well.

**Comment by NathanKell** [comment]
Woot!

**Comment by pap1723** [comment]
I integrated this within the XLS file. This pull will cause Merge Conflicts.

**Pull request closed without merging**
