### PR TITLE
Price and place the Gemini Lander SM (and typo fix).

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by stratochief66** [comment]
@ahmedcharles 

I think that the entry cost has an extra zero in it, or am I mistaken?

**Comment by rsparkyc** [comment]
look like he added 20% to the FASAGeminiUtilityPack, which has an entry cost of 178000, so it looks like the number is right (unless what it's based off of is wrong)

**Comment by ahmedcharles** [comment]
Yeah, I don't remember, but that's what the comment says. The values look correct for being 20% more.

**Comment by stratochief66** [comment]
The original is wrong then. Generally, the entry cost is 20x the part cost, this is 200x

**Comment by stratochief66** [comment]
@ahmedcharles could you adjust your addition & the original to be 20x?

**Comment by ahmedcharles** [comment]
I accidentally deleted the repo, so I had to create a new pr. #618

**Pull request closed without merging**
