### PR TITLE
Added sounding rocket altitude records

### PR DESCRIPTION
**Pull request by Shurikeeen**

### CODE REVIEW

**Comment by NathanKell** [comment]
Awesome! :)

Quick question: Isn't 'name' not shown and only used internally? That's why I gave it a machine-readable name (like part names)...

**Comment by Shurikeeen** [comment]
I think so. Does it matter what the title is?

**Comment by NathanKell** [comment]
The title will be the thing actually shown in the GUI, so yes it matters what the title is. The name field, however...MM can't deal with things with spaces, and it's best to make names shorter (and more info-rich) so they can be easily tagged by other things. So I'd definitely suggest having a name that uses only alphanumeric characters and dashes and underscores, and leave the prettiness to title. :)

**Comment by Shurikeeen** [comment]
Ah, I see.

**Comment by Shurikeeen** [comment]
Things are kinda borked in the current commit. I'm releasing a patch what also should add speed records in maybe the next half a hour.

**Comment by NathanKell** [comment]
Ah, sorry, should have asked before mergi...ah, screw it. 1min.

**Comment by NathanKell** [comment]
Added you. No more PR jiggery. :)

**Pull request merged**
