### PR TITLE
Programs and Launch Complexes

### PR DESCRIPTION
**Pull request by NathanKell**
Programs is a new way of playing RP-1, where contracts are grouped into overarching Programs. Use the Administration Building to select your starting Program(s) and go from there. You will only have access to the contracts appropriate to your current Program(s), and those contracts will only reward rep. Income comes from the your programs' budgets, though you also get a large subsidy (towards salary and other maintenance costs). This subsidy increases year-over-year until the mid-60s, and varies between a floor and 2x the floor based on your level of rep (1 unit of rep = 100 funds).

[Here is a wiki page with some documentation](https://github.com/KSP-RO/RP-0/wiki/Launch-Complexes-and-Programs-Conversion-Guide)

### CODE REVIEW

**Comment by Tsits11** [comment]
I strongly feel that the way the contract system works right now- we’re losing money! Simple as that! There’s a number of times I’ve had a contract finished early, only to complete it and lose the funding for the remaining years 😣plus the reputation reward is pathetic, shouldn’t there be a bonus for a quick completion ?

**Comment by NathanKell** [comment]
This is not the Programs issue tracker. Please actually use that. The link is in the pins in discord (which really, really need to be read thoroughly) and I've just added a link in the OP.

**Comment by Gordon-Dry** [comment]
After I updated to the artifact of https://github.com/KSP-RO/RP-0/pull/1696/commits/aef072075b732adbafdcf9dd474430db28287725 I got this in the VAB on the first try of right-clicking on any part of a loaded vessel that had no issues in the last session (besides a design issue, that's why I loaded it):
```
InvalidCastException: Specified cast is not valid.
  at BaseField`1[K].GetValue[T] (System.Object host) [0x00007] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionToggle.GetFieldValue () [0x00011] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionToggle.Setup (UIPartActionWindow window, Part part, PartModule partModule, UI_Scene scene, UI_Control control, BaseField field) [0x0000f] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionWindow.AddFieldControl (BaseField field, Part part, PartModule module) [0x00073] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionWindow.CreatePartList (System.Boolean clearFirst) [0x002bc] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionWindow.Setup (Part part, UIPartActionWindow+DisplayType type, UI_Scene scene) [0x0006a] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionController.CreatePartUI (Part part, UIPartActionWindow+DisplayType type, UI_Scene scene) [0x000f7] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionController.SelectPart (Part part, System.Boolean allowMultiple, System.Boolean overrideSymmetry) [0x001a7] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionController.HandleMouseClick (UnityEngine.Camera cam, System.Boolean allowMultiple) [0x0003f] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UIPartActionController+<MouseClickCoroutine>d__39.MoveNext () [0x00082] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <12e76cd50cc64cf19e759e981cb725af>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
 
(Filename: <39c0323fb6b449a4aaf3465c00ed3c8d> Line: 0)
```
from then on it was spammed and I could not use the UI properly anymore.

The PAW UI was just a tlny rectangle with an outline but no contents.

I have no clue what the reason is, it just happened after the beforementioned last change.

I will try the newer artifact of https://github.com/KSP-RO/RP-0/pull/1696/commits/67d59c3a90f630d7837351ccdbcc08e468085f1a for now and hope it's the fix.

For curiosity, here are the logs:
[2022112201.zip](https://github.com/KSP-RO/RP-0/files/10069133/2022112201.zip)

**Comment by Falki-git** [comment]
Everything works fine for me with the latest commit.

**Pull request merged**
