### PR TITLE
M-1, F-1B price fixes

### PR DESCRIPTION
**Pull request by Capkirk123**
Update the prices of the M-1, F-1B according to the following issue.
https://github.com/KSP-RO/RP-0/issues/1170#issuecomment-571686739

### CODE REVIEW

**Comment by siimav** [comment]
Could you fix the conflicts?

**Comment by pap1723** [comment]
Please re-submit this, but do not include any config files.

**Comment by Capkirk123** [comment]
Yeah, no problem. Github and parts browser dont play nice apparently.

**Comment by pap1723** [comment]
Yeah, it is more that I pushed different configs and it created a conflict. Best way to do it is to make the JSON changes and then submit the PR.

**Pull request closed without merging**
