### PR TITLE
A little maintenance on the README

### PR DESCRIPTION
**Pull request by adouge**
Fixed a few typos; also changed the recommended modlist a bit.

 Added a link to installation guides for details, since maintaining a second mod list on the front page seems.. unneeded?

### CODE REVIEW

**Comment by jwvanderbeck** [comment]
FYI: Checks are failing because it is from an external fork

**Comment by adouge** [comment]
Is it going to retry on each commit? No need to waste CI minutes on a readme..

**Comment by jwvanderbeck** [comment]
> Is it going to retry on each commit? No need to waste CI minutes on a readme..

The CI doesn't cost anything.  Technically the download from S3 does but I'm not worried about it.

**Comment by adouge** [comment]
Closed b/c I accidentally deleted my fork. Will come back to this in dec/jan

**Comment by MikeOnTea** [comment]
Your changes are not lost, btw, they're still on github and you can recover them.

**Pull request closed without merging**
