### PR TITLE
Add configs for SpaceX Capsules

### PR DESCRIPTION
**Pull request by StonesmileGit**
Added configs through Part Browser, Avionics and Crew Training times.

Starship Lunar to follow when added to https://github.com/KSP-RO/ROCapsules/pull/70.

Needed to add RP-1 support for https://github.com/KSP-RO/ROCapsules/pull/70

### CODE REVIEW

**Comment by StonesmileGit** [comment]
Everything is now added.

The data in this PR is provided by @Vader111, Please let me know if something doesn't add up or is wrong.

**Comment by vader111** [comment]
(Ready To Review)

**Comment by siimav** [comment]
Why does it have configs for ROHeatshields in there? Also the .cfg files have conflicts now.

**Comment by StonesmileGit** [comment]
A quick look suggest that the order of stuff in the ROH file got switched around without me doing anything... Could be wrong

**Pull request closed without merging**
