### PR TITLE
Move Gemini LEO heatshield to capsules node

### PR DESCRIPTION
**Pull request by lpgagnon**
Following the lead of ROCMercury: it's not possible to unlock the
capsule node without unlocking Human Rated EDL, which already
provides a suitably-sized shield. Don't force players to unlock
Early Landing just to use the "right" shield

### CODE REVIEW

**Comment by siimav** [comment]
> Don't force players to unlock Early Landing just to use the "right" shield

I only see them having to unlock the HS node as a good thing

**Comment by siimav** [comment]
IRL Gemini HS is a significant upgrade over Mercury. I know there isn't any difference ingame between the 2 right now but I would like to change it at some point.

**Comment by NathanKell** [comment]
Uh, since when is there no difference ingame? Was there a big heatshield rebalance pass that I missed? Gemini's shield was tuned to support (very careful) lunar returns, which the LEO shields can't.

**Comment by lpgagnon** [comment]
approximately since
1) RO grew a generic scheme for applying properties to heatshield, and
2) ROC Gemini CM got split from its shield, and separate LEO- and Lunar-rate shields were added

**Comment by NathanKell** [comment]
That would explain, yeah. Thanks!

**Comment by NathanKell** [comment]
Snice we're in the process of adding a Gemini level of shield, closing this.

**Pull request closed without merging**
