### PR TITLE
Flyby Contracts for the gas giant moons

### PR DESCRIPTION
**Pull request by leudaimon**
Creates Fly-by contracts for the gas giant moons. 
- Rewards (loosely) based on the difference between Mars and Phobos fly-bys
- Minimum distance kept the same 20Mm, given all flyby missions (except the moon) have this
- Deadline is the same as the one for parent body flyby
- Requirement is parent body flyby

### CODE REVIEW

**Comment by NathanKell** [comment]
Good stuff! Will have a look asap! :)

**Comment by leudaimon** [comment]
@NathanKell, I'm doing the stuff from #566 in this branch: https://github.com/leudaimon/RP-0/tree/UncrewedExploration given it's big and may have bugs. Is this the "correct" way?

**Comment by NathanKell** [comment]
Coming up for a bit of air, gonna try to get back to this. Apologies.

**Comment by leudaimon** [comment]
Good point. I was in doubt about the reason for the planet flybys to have the same altitude for all planets. That's why I kept the same for the moons. I guess 2,000km might be enough? 

Btw, these contracts will need the corrections for the CC update also.

**Comment by leudaimon** [comment]
Sorry for the spam, fixed this in the online editor, don't know how to edit multiple files in a single commit here.

**Comment by rsparkyc** [comment]
Was looking at merging this, what exactly do these need as far as CC updates?

**Comment by stratochief66** [comment]
I looked through them, but I don't know enough CC to answer that myself. We'd either need to leave these be for now, or else someone would need to learn enough CC.

**Comment by rsparkyc** [comment]
I remember doing changes for the contracts we had already to update them to the new version.  The main thing I remember doing was removing the weight parameter, which this doesn't have.  I'm trying to load them into my setup now to see what happens.

**Comment by rsparkyc** [comment]
these seem to load fine in my install

**Comment by stratochief66** [comment]
Nope!

**Pull request merged**
