### PR TITLE
Moved the GCRC to solids1956

### PR DESCRIPTION
**Pull request by nepphhh**
Based on a short conversation with Mike, seems historical reasonable given Vanguard development dates.

### CODE REVIEW

**Comment by lpgagnon** [comment]
Given that this seems like a historical no-brainer, it'd be good to understand why it wasn't there in the first place...

**Comment by nepphhh** [comment]
As I don't know how to change that, I invited both Mike and Siimav as collaborators on the fork.

**Comment by siimav** [comment]
That fork has been tainted by QB so I'm not touching that even with a long stick.
But I'm pretty sure Mike meant those year values:
https://github.com/KSP-RO/RP-0/pull/1129/commits/390dd0fca66072acdcd5d3a47d02f7535bef24b5#diff-498fee6f6ab34bc32e151b47cdd23896R1830

**Comment by nepphhh** [comment]
The main branch is QB-infested, but this branch on the pull request is fresh off RP-0:master. I'll take a swing at it.

**Comment by lpgagnon** [comment]
The tech node's description is already "1956-1957 Solid Rocket Engines". The internal name 'solids1956' matches the other nodes (solids1959 for 59-90 engines, etc)

**Pull request merged**
