### PR TITLE
Move AJ10-27 config to Basic Rocketry

### PR DESCRIPTION
**Pull request by nepphhh**
The AJ10-27 first flew in 1955 as the Aerobee AJ10-27 and as the Aerobee RTV-N-10c, putting it on the very tail end of Basic Rocketry (1952-1955). It definitely doesn't belong in early Rocketry (1951-1952).

Sources: https://space.skyrocket.de/doc_lau_fam/aerobee.htm http://www.astronautix.com/a/aerobeeaj10-27.html

### CODE REVIEW

**Comment by siimav** [comment]
Any other thoughts on this? Maybe this choice was done based on game balance considerations to have something worthwhile in the Basic Rocketry node?

**Comment by leudaimon** [comment]
Yeah, I think for game balance it makes sense to keep it where it is.

**Comment by siimav** [comment]
Another thing to consider is that none of the pre-1956 nodes have any year numbers associated with them. For example the first aviation and rocketry nodes already contain parts that are from the 1945-1950 era (Derwent, XASR, etc).

**Comment by siimav** [comment]
Closing this issue because from the gameplay perspective the current placement makes more sense.

**Pull request closed without merging**
