### PR TITLE
Add Tantares_Engine_C, same as A and B.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by SirKeplan** [comment]
interesting, this has brought to light an error in the tree, the `Tantares_Engine_A` is for Soyuz T onwards, which should be in a later node, it first flew in 1979.

**Comment by ahmedcharles** [comment]
Which node represents 1979?

**Comment by SirKeplan** [comment]
`specializedControl` is probably the place for this.

Though I must say that nodes aren't really designed to match specific years, as sometimes new tech comes along based on fairly old designs.

**Comment by ahmedcharles** [comment]
That's probably slightly better. :)

**Comment by SirKeplan** [comment]
Looks good to merge, unless anyone has an idea for the price of these service modules, they should be different in real life.

**Pull request merged**
