### PR TITLE
Experiment cooldown & shielding

### PR DESCRIPTION
**Pull request by PhineasFreak**
* Add cooldowns for the experiments (cannot be rerun immediately) and
"is shielded" checks.
* Remove some trailing spaces.

[Alternate diff (ignoring whitespace changes).](https://github.com/KSP-RO/RP-0/compare/master...PhineasFreak:RP0-Experiments-Cooldown-Shielding?w=1)

### CODE REVIEW

**Comment by PhineasFreak** [comment]
Note to self: find what the is problem with the experiments stating that "Cannot perform experiment, must wait 00:00:00".

**Comment by PhineasFreak** [comment]
@stratochief66 did you have the same problem with the experiments as i have? Because i was unable to perform the experiments due to the message stated above.

**Comment by stratochief66** [comment]
Odd, no I didn't. It looks like the way you squared #612 will remove these changes, so that will give us a chance to try again?

**Comment by PhineasFreak** [comment]
I tried at least three times to debug it with no success (new installation, only the minimum mods, making sure that everything is updates) . Every time i got the same message.

**Pull request merged**
