### PR TITLE
B 737 - crew cabins, tail

### PR DESCRIPTION
**Pull request by winged7**

### CODE REVIEW

**Comment by OtherBarry** [comment]
Dayum dude. Your on a roll. You've been taking up 90% of my inbox for the
past few days.

**Comment by NathanKell** [comment]
It's probably best to hold off on these until RO supports them? As Mk3ish parts, I guess they'd be sized to fit the B-52 cockpit?

**Comment by winged7** [comment]
SXT crew cabins are already supported by RO.

**Comment by winged7** [comment]
screen from my game:
http://i.imgur.com/YBS3EbG.jpg

supported by RO, not supported by RP-0.

**Comment by NathanKell** [comment]
Welp, I just searched the RO repo, and no hits for LMKIIIAircraftFusLong or LMkIIIAircraftFus ....

**Comment by winged7** [comment]
Weird, I will make support for them soon.

**Comment by winged7** [comment]
https://github.com/KSP-RO/RealismOverhaul/pull/567 SXT: B737 fuselage

**Pull request merged**
