### PR TITLE
Update Projects for KSP 1.8

### PR DESCRIPTION
**Pull request by CalvinMaclure**
Giving space stations more of a reason for being. Basically, much in the same way that comm sat or weather sat payloads exist, there could be a science payload. The idea would be that this represents experiments that must be done in a microgravity environment and once completed would generate funds or science or both. Each unit of science payload would require x hours of research by scientists to complete. Having more scientists working on it at once could improve completion times. Higher complexity experiments could require more than one crew to perform. There could even be various types of science payloads and various complexity levels requiring more time to complete and generating greater gains.

### CODE REVIEW

**Comment by siimav** [comment]
???

**Comment by CalvinMaclure** [comment]
What? Did I do something wrong? Or is the request unclear?

**Comment by Starwaster** [comment]
@CalvinMaclure look at the files being changed.

**Comment by CalvinMaclure** [comment]
Yeah I thought this was the proper place. But I could be completely wrong. I'm not super familiar with GH. Feel free to delete the PR.

**Comment by Starwaster** [comment]
The problem is the files themselves that you are submitting. They're just project files. And they're actually changes from a commit that @siimav did himself. Look at the date on them. Look at the commit itself.

Something went wrong on your end because I seriously doubt (based on your description of the PR) that these are even the files you meant to submit.  We're not even sure how you accomplished this. I have a vague notion that it could happen if you were working directly off of the Master branch instead of creating a separate branch locally for the changes you wanted to work on. Can't say for sure.

But somewhere you have some files you were working on that you wanted to submit and they are not in this request.

**Comment by CalvinMaclure** [comment]
Ah... yeah. It's the master's branch thing you mention. That would have to be it... Just to be sure I don't muck anything up removing this PR, what's the safest way? Just ''Close and comment"?

**Comment by Starwaster** [comment]
yeah just close

**Comment by CalvinMaclure** [comment]
Ok. Thanks, and sorry for the bother! :S

**Pull request closed without merging**
