### PR TITLE
Add proc-fairing tech upgrades

### PR DESCRIPTION
**Pull request by Capkirk123**
Add proc-fairing upgrades, decreasing fairing density as they are unlocked. Requires dev PF to properly enforce fairing density.

### CODE REVIEW

**Comment by NathanKell** [comment]
Targeted PLC because it's save-breaking.

**Comment by DRVeyl** [comment]
Bah.  Ship It Anyway!

**Comment by DRVeyl** [comment]
BTW, this appears to have been based off another branch [SMERCH/Energia/Alcentar patches?]

**Comment by NathanKell** [comment]
Yeah I haven't done a rebase and force push in a bit.

**Comment by NathanKell** [comment]
Ugh should not have squashed this. Oh well. It'll get fixed in the next rebase.

**Pull request merged**
