### PR TITLE
Support LE-5 (FRE)

### PR DESCRIPTION
**Pull request by Zarbizaure**
is the price/placing ok?

### CODE REVIEW

**Comment by NathanKell** [comment]
The engine should probably be about half to two thirds the total stage cost. In terms of placement, it should be in hydroloxTL5, it was designed and put into service in the 1980s. You placed it alongside the RL10, designed in the 1950s. ;)

**Comment by Zarbizaure** [comment]
I saw stage cost = 30M so engine cost ~15M, in 1992 USD.and I converted it in 1965 USD.
About the placing, why not, but it use the same technology as the RL-10...it was just developped later...
(also, I will add pricing & placing by engine config in a later update of FRE, so probably LE-5B and B2 will  end in hydroloxTL5, with a slightly modified cost)

**Comment by NathanKell** [comment]
The Merlin 1D Full Thrust uses the same "technology" as the LR79 first flown in 1957. That does not at all mean that the Merlin 1D is at the same _level of technology_ as the first LR79. We place parts based on when they were designed and flown (with a few odd exceptions, but this is not it).

Let's compare: The LE-5 uses a gas generator cycle (same as the J-2 and LR87LH2, _not_ the same as the RL10's expander cycle). With that cycle, it gets ~450s in vacuum. The J-2, a hydroloxTL3 engine, gets only about 420.

**Comment by Zarbizaure** [comment]
Yes, you're right. And the LE-5 has an advanced spark ignition system (rated for 16 restart). So I should move it to TL7? If I do this, I will probably cost the other configs in the same node, since they were'nt really developped later (LE5-B2 was developped in 2003, but it's mainly an improvement in term iof reliability).

**Comment by NathanKell** [comment]
The base LE-5 was designed and flown in the mid eighties, and therefore should be in hydroloxTL5 as I mentioned above. The later variants...well, IIRC the LE-5A was a near-complete redesign (even switched to expander cycle!), so maybe TL6 makes sense?

**Comment by Zarbizaure** [comment]
well I'm so stupid. Moved everything to TL7 and you said TL5 (facepalm)
I will move this back to TL5, and cost my other configs for TL6.

**Comment by NathanKell** [comment]
No worries. :)

I gotta sleep though, I'll catch up in the morning!

**Comment by Zarbizaure** [comment]
No problem!
The engine configs placing (for the LE-5 as well as for the Vikings) will probably come in the next release along the LE-7 engine.

**Comment by NathanKell** [comment]
Thanks! :)

**Pull request merged**
