### PR TITLE
Support new SSTU XLR81 engines

### PR DESCRIPTION
**Pull request by Zarbizaure**

### CODE REVIEW

**Comment by jwvanderbeck** [comment]
Should additionally add cost modifiers from one to the other I think so that the pricing remains as it is now.

**Comment by Zarbizaure** [comment]
of course I'll add them.

**Comment by Zarbizaure** [comment]
so where is this Agena entryCost? I did not found it, maybe it's not properly configured?

**Comment by SirKeplan** [comment]
Closing this as i think it's covered in #577 , and it looks to me the entrycostmodifiers aren't necessary to add, these are different variants of the engine.

correct me if i'm wrong.

**Pull request closed without merging**
