### PR TITLE
Delta LTTAT avionics upgrade

### PR DESCRIPTION
**Pull request by ctiberious**
Slight increase to allow the avionics part designed for the LTTAT to function on the Delta 0900 rocket.

### CODE REVIEW

**Comment by NathanKell** [comment]
I'd suggest just bringing this up to 130 (was 120), i.e. in line with the standard 2m unit.

**Comment by ctiberious** [comment]
Isn't the early 2m unit a 120?

**Comment by NathanKell** [comment]
9423a221864ff5429d346dfe5e1c6e5b35137859 :)

**Comment by ctiberious** [comment]
Ah.  It's about to be updated.  Gotcha.  130t is probably a bit overkill for the Thor since it had a much lower payload than the TItan and Atlas, but I've updated that avionics package all the same.  :)

**Pull request merged**
