### PR TITLE
K2 Command Pod RP-0 support

### PR DESCRIPTION
**Pull request by PhineasFreak**
Change log:

* Add RP-0 support for the [K2 Command Pod](http://forum.kerbalspaceprogram.com/index.php?showtopic=155013) (Gemini style).

### CODE REVIEW

**Comment by leudaimon** [comment]
Cool! Any reason for this to have a different pricing than the FASA and Tantares Gemini?

**Comment by PhineasFreak** [comment]
The K2 includes the Reentry Control System in the pod structure. In FASA and Trails these parts are separate. So:

* RCS (cost/EntryCost): 720/36000
* Pod (cost/EntryCost): 5400/286000

with the sums of these two to be 6120/322000. These values should probably be tweaked a bit since it is not a Gemini CM per se.

**Comment by leudaimon** [comment]
Oh, ok! I tried to find stuff that could be included in the K2, but was looking for parachutes and this kind of stuff.

**Comment by stratochief66** [comment]
Nice! A non-FASA, non-Russian 2 crew part.

**Pull request merged**
