### PR TITLE
New parts

### PR DESCRIPTION
**Pull request by winged7**
- GEM 63
- GEM 63 XL
- Soyuz orbital module from Habitat pack
- Soyuz heatshield (stock)
- stock APASport

### CODE REVIEW

**Comment by NathanKell** [comment]
There's already a Soyuz heat shield, the new one should be reference to that. Same with the APAS port. Rest looks reasonable.

**Comment by winged7** [comment]
Price for the APASport is the same as for the other APAS portas (there are two of them).

As to the Soyuz heatshield - I can't find other heatshield so deleted for now.

**Comment by NathanKell** [comment]
Ya, it wasn't about the price, it was about using the reference operators. :)

**Comment by winged7** [comment]
Done.

**Pull request merged**
