### PR TITLE
Add RZ config

### PR DESCRIPTION
**Pull request by Capkirk123**
Add configs for the Rolls Royce RZ series engines

### CODE REVIEW

**Comment by seymonsters** [comment]
The engines use on Blue Streak or the proposed Hydrolox Engines (or both?)

**Comment by seymonsters** [comment]
Considered adding in the RZ.10? Was very much a paper rocket engine but wouldn't be the first such inclusion?

The interesting challenge would be the Stentor engine with its 2 different thrust chambers etc...

**Comment by Capkirk123** [comment]
I was previously unaware of the existence of the RZ.20. However, given that it was test fired, it does meet the criteria for being added to RO. I'll have to make up most of its performance though unfortunately, there seems to be very little data on it.

**Comment by seymonsters** [comment]
Maybe base it on the RL10A-3 due to similar predicted thrust? And use a similar developmental pathway ( in the same way RZ.1 and RZ.2 followed the S3/S3D/LR79 route?

**Pull request closed without merging**
