### PR TITLE
Contract: First Space Station

### PR DESCRIPTION
**Pull request by Brummi1234**
Changed the required crew from 4 to 3 so it can be completed with Salyut 1, the actual first space station.

### CODE REVIEW

**Comment by NathanKell** [comment]
Doesn't it only require two crew, but space for four? Salyut, by KSP terms,
had space for 6 (or more) with Soyuz docked.

Sent by my thumbs, slowly.

**Comment by Brummi1234** [comment]
It needs to be uncrewed and have space for 4. So if you bring 2 or 3 up you fail the uncrewed check.
Pap mentioned in the Disord it was at 4 to stop people using Apolle (or Soyuz i guess) as a space station

**Comment by pap1723** [comment]
Any thoughts on this? What @Brummi1234 says is true, but there is also the point that the new version of the contract works by putting an Apollo capsule in orbit and putting crew there.

What other requirements should there be for something to be considered a "Space Station". There has never been one launched without Solar Panels, correct? What else? A specific amount of a resource?

**Comment by ec429** [comment]
Can we not just have a ModuleTagStationHabitation, or can CC not see those?

**Comment by pap1723** [comment]
Yes, we would just need to add the tag and then tag the parts. It makes sense.

**Comment by Brummi1234** [comment]
Hi, yeah that's what i had in mind with issue 1068 (don't know how to link it on mobile) but forgot to close this pr :)

**Comment by lpgagnon** [comment]
If someone _wants_ to keep an apollo crewed and powered long enough to qualify as a space station, what's the rationale for preventing it?

Only obvious one I see is "too cramped". Kerbalism deals with that among its stress factors; what would be the natural non-kerbalism way to handle the concept?

**Comment by SerinaTsukaya** [comment]
Well if you put an empty Apollo capsule in orbit as your station then dock another Apollo craft to it, then i mean, it's kind of a station in a sense? Maybe we should change the contract goal instead to require you to have two craft launched at two different times dock in orbit with twice as much crew capacity as there is actual crew. You won't stop people from docking an apollo with an empty apollo, but at the very least some effort has to go into it. On a different, note, what use is there for non kerbalism space stations? Does the lab function as it does in stock?

**Comment by Brummi1234** [comment]
The reason for not allowing apollo/soyuz as a station is probably that you should have to research and pay for a station part to get the contract money.

**Pull request merged**
