### PR TITLE
SSTU Merlin engines

### PR DESCRIPTION
**Pull request by Zarbizaure**
Merlin 1B/1Bvac (slighly less expensive than 1C) and XLR81 (part in developpment)

### CODE REVIEW

**Comment by Temeter** [comment]
Wouldn't price the merlin alone. I did just copy the Merlin-1D(+1Dvac) prices for the other merlin engines.

1D is the only creddited price from an interview (which might be already outdated), while the Dvac price is an assumption.
Guess you could make the A/B/C progressively cheaper, tho, that way we'd have more consistent pricing.

**Comment by Zarbizaure** [comment]
Make them cheaper? It make sense but then the entryCost needs to be more and more expensive. Do we have any entryCost source right now? (And, it means we'll have to use entryCostSubstractors).
I'm going to sleep now, so if anybody else want to work on that...

**Comment by Zarbizaure** [comment]
I changed SL versions to 205/195/185/175 and vacuum versions to 220/210/200. Maybe we could do better, but I honestly don't know withouth sources.

**Comment by Temeter** [comment]
Sorry, my post was a bit messy i guess, I blame being distracted and bad english.^^
 
The Merlin-1D is 175/200, following real sources, and you brought up the idea of making the 1B cheaper. So I was saying currently Merlin-1A/1C still cost 175/200, so they maybe should be cheaper as well!

Entry cost is a bit of a mess anyway. Merlin engines are developments based of each other.

**Comment by Zarbizaure** [comment]
That's why we should use entryCost multplier (or substractor). That way, if we unlock one of them, all of the other merlin engines will have their prices reduced. Maybe I'll do that tonigh.
(And I've also a bad english, I'm french)
I don't think earlier should be cheaper (after some though) because the 1A/1B were just prototypes so they were more expensive to produce (but less expenseive to developp).

**Comment by Temeter** [comment]
German here. ;)
I don't think we should make engines more expensive on the base of them being prototypes. A lot of Realism Overhaul/RP-0 is about making your own alternative history. I think NathanKell made that point himself: You basically can play like research on nuclear engines never stopped after the NERVA (which only had a ground based prototype).

So if you buy rockets out of Merlin-1B's, then they aren't prototypes but actual mass production in your history.

**Comment by Zarbizaure** [comment]
I can speak german but I don't think RO guys will like that x)
Yes, but an engine that is produced only in a little number won't have its cost lowered; if you produce a large amount of engines, their price will decrease over time (or for any other stuff).
That's why I think a decreasing curve would be good. Maybe @NathanKell could help us?

**Comment by Temeter** [comment]
Good point, that's exactly what came up in another issue: https://github.com/KSP-RO/RP-0/issues/490

Russian engines like the RD-253 are ridiculous cheap, because russians/soviets were better at mass producing, while a lot of the american material was custom made.

**Comment by Zarbizaure** [comment]
I though exactly to this Github issue.

Anyway, since the Merlin 1B and 1C are in the same node, players will probably never play with the 1B. But it make sense since they were never used on a rocket (for others reasons like reliability, and the lack of regenerative cooling).

**Comment by Zarbizaure** [comment]
I'm closing this and I'll open a new PR from my master branch.

**Comment by Zarbizaure** [comment]
It should be fine now. Sorry if I closed/reopened, I'm still pushing from my pach-6 branch.
The placement is probably far from perfect, but it's better than nothing! Plus every player will at least purchase 2 merlin engines, which lowers to the minimun price mots of the time.

**Comment by Temeter** [comment]
Github is a mistery of our times.

If nobody does it in the meantime, i'll check those files (+RO) ~tomorrow. Atm busy fixing my broken, half updated and incomplete installs, as well as checking SSTU pricing fixes.

**Comment by Zarbizaure** [comment]
I don't have time to test it too; but I think it should be ok.
We should also definitely set entryCostModifiers for the RL10s too.

**Comment by NathanKell** [comment]
Whoops, this conflicts now. Also, are the prices corrected for inflation?

**Comment by Zarbizaure** [comment]
For the prices I'm based on what Temeter found for the Merlin D. I don't know how accurate it is, however it seems to be a reasonable price.

Why the hell is there conflicts? :P anyway you can just copy/paste these few lines into the designed files; I'll still look at it later and try to find the error.

**Comment by Zarbizaure** [comment]
so, 2.17 millions for one merlin 1D (https://www.quora.com/How-much-does-it-cost-to-produce-a-single-Merlin-engine-in-SpaceX-rockets)
Which is 369 funds (1965) so the engines are indeed slightly underpriced. I'll higher the cost a bit.

**Comment by jwvanderbeck** [comment]
There are probably conflicts because a previous PR that was merged changed the same file as you.

Sadly this is what happens when the project accumulates a ton of PRs then accepts them all at once rather than over time.

**Comment by Zarbizaure** [comment]
Yes I understood that...
Obviously that's a small PR so maybe people with merging rights can copy/paste this manually? Otherwise I would have to start a new PR, I guess?

**Comment by jwvanderbeck** [comment]
strangely your branch is trying to merge files it shouldn't be, so let me look at it

**Comment by jwvanderbeck** [comment]
ok looking at this now.. let me see if I can clean it up.

**Comment by jwvanderbeck** [comment]
So basically your changes on #539 are conflicting with this now.  I'm fixing it now.

**Comment by jwvanderbeck** [comment]
Cleaned and merged

**Comment by Zarbizaure** [comment]
thanks! :-)

**Pull request merged**
