### PR TITLE
Migrate RL10 Configs to RP-0

### PR DESCRIPTION
**Pull request by SirKeplan**
there will be a RO PR to go with this soon

Don't Merge yet, needs checking/testing.

### CODE REVIEW

**Comment by SirKeplan** [comment]
Shouldn't we start with configuration = RL10A-1 instead of the RL10A-3-3 ?

**Comment by SirKeplan** [comment]
should be good to go.

**Comment by NathanKell** [comment]
@SirKeplan  Oh, missed the question. Yes, we should start with A-1, and I thought I had a patch to do just that. >.>
RO starts with A3-3 because that's the most famous/generally-used model, but RP-0 should start with A-1. Though as you say it'll automatically bounce back to the first available.

**Comment by SirKeplan** [comment]
when I tested it actually did not bounce back to the first available, you can actually use a locked config if it is the default one.

**Comment by NathanKell** [comment]
That sounds like an RF bug...

**Pull request merged**
