### PR TITLE
RL10 from Chaka  - configs

### PR DESCRIPTION
**Pull request by winged7**
https://github.com/KSP-RO/RP-0/pull/317

https://github.com/KSP-RO/RP-0/pull/327

### CODE REVIEW

**Comment by NathanKell** [comment]
So this is the combination of #317 and #327 ?

**Comment by NathanKell** [comment]
Or, if not...not sure what the references mean.

**Comment by winged7** [comment]
No, this isn't combination of #317 and #327. It's a whole different thing:  there are 6 various configs for this engine so every other version needs its own pricing. RL10C-1 will cost you 6000 but for CECE-Base you will pay only 3800. The same as for FASA RL10 configs.

**Comment by NathanKell** [comment]
Ok. Um, so why the links then? I'm confused.

**Comment by winged7** [comment]
because config for Chaka RL10 engine is entwined with placing & costing Chaka RL10. Isn't?

 You can't just left RL10 with 5300 price because there are various config for it: some are cheaper, some are more expensive.

**Comment by NathanKell** [comment]
Ah, ok. That's the sort of thing that should all be in one branch though (and there'd be fewer merge collisions :) ).

**Comment by NathanKell** [comment]
Uh, also, this file isn't of extension .cfg and so KSP won't see it...

**Comment by winged7** [comment]
updated to .cfg extension

**Pull request merged**
