### PR TITLE
Add science core to everything without avionics or crew control

### PR DESCRIPTION
**Pull request by aw1621107**
This eliminates the need to explicitly enumerate all probe cores that
need to have science cores added.

### CODE REVIEW

**Comment by NathanKell** [comment]
That should probably be in a later pass to ensure it runs after all avionics are added?

**Comment by aw1621107** [comment]
`:AFTER[RP-0]`, since it looks like all the avionics are in `:FOR[RP-0]`? Or will this require a `z` prefix, e.g. `zRP-0Avionics`?

**Comment by NathanKell** [comment]
AFTER should be fine I think!

**Comment by aw1621107** [comment]
Done!

**Pull request merged**
