### PR TITLE
Update tree.yml

### PR DESCRIPTION
**Pull request by mcirish3**

### CODE REVIEW

**Comment by jwvanderbeck** [comment]
You need to watch your spacing.  YAML is absolutely anal about spacing and it must be **exact** or things won't work.

**Comment by mcirish3** [comment]
I will try and watch it.  These are my first edits.

Date: Fri, 20 Mar 2015 15:41:32 -0700

**Comment by pjf** [comment]
@mcirish3 : You are awesome! Thank you so much for this! Don't stress too much abut the spacing, our QA bots will catch it if something is wrong, and it's dead easy for us to fix in merge. Simply knowing where parts should go is fantastic.

Are all these parts from AIES? I don't recognise all the part names. :)

Thanks again!

~ Paul

**Comment by NathanKell** [comment]
@mcirish3 looking this one over, radr is the RTG, yeah? Probably shouldn't go in the rocketry node then. I'd suggest putting it in scienceTech, that's the first 'electronics' node and is the right year or so for SNAP-3 (what *is* radr made? SNAP-3 or a later one?).

Also, as a general rule it's a good idea to comment next to each part and say what it is (in RO-land) if it's not immediately obvious, for example # Aestus by the galaxvr2. Just makes our lives easier going forward. :)

Rest looks awesome, thanks again!

**Comment by pjf** [comment]
The power branch goes: `scienceTech`, `electrics` (1964), `advElectrics` (TL4), `largeElectrics` (TL5), `specializedElectrics` (TL 6), `experimentalElectrics` (TL 7). Actual reactors have their own nodes.

The SNAP-3 provided 2.5W of power. that's 0.0025 EC/sec (assuming 1EC = 1kJ), or 9EC/hr. That's enough to power "science cores", but nothing with avionics. I'd pop it in `electrics` rather than `scienceTech`, but honestly happy with either.

**Comment by mcirish3** [comment]
radr is the SNAP-19.  The project was started in 1963 and finished in 1968 do you need me to go in and edit my fork or is this something you guys correct on the back end.

Date: Sat, 21 Mar 2015 01:07:54 -0700

**Comment by mcirish3** [comment]
Thanks for the heads up this part was the SNAP-19 development started in 1963 and ended 1968.  I have it down for TL2 which if I remember correctly would have it fall in electrics.?  do you need me to update this or is this something you can do on the back end?

Date: Sat, 21 Mar 2015 03:32:50 -0700

**Comment by mcirish3** [comment]
Hi Paul,
No not all of them are AIES,  they are in a some what random order.  I am working linking up what I can find.  The file I linked  should help you see how I am working on this.   

Date: Sat, 21 Mar 2015 00:48:33 -0700

**Comment by NathanKell** [comment]
SNAP-19 should go in advElectrics -- it wasn't used until 1968, and its major uses were in the early 1970s. Let's reserve an earlier spot for something configured for SNAP-3.
As this has not been merged yet, it's best if you fix things on your end, since otherwise we would have to either merge and then fix, or fix by pull request to your pull request. :)

**Comment by mcirish3** [comment]
Finished I think

Date: Sat, 21 Mar 2015 16:18:25 -0700

**Comment by pjf** [comment]
Merged with thanks! :)

**Pull request merged**
