### PR TITLE
Engine identicalPArts and Entry Cost Modifiers

### PR DESCRIPTION
**Pull request by smartdummies**
Updates to the IdenticalParts and EntryCostModifiers, moslty AJ10s

### CODE REVIEW

**Comment by NathanKell** [comment]
Um, is the bluedog-DeltaK-AJ10 not actually the Delta K one? Because Delta K's AJ10 was like the last AJ10, so it'd be AJ10-Adv.

**Comment by NathanKell** [comment]
Poke

**Comment by smartdummies** [comment]
Ok let me go back and take a look

**Comment by smartdummies** [comment]
Doh, bad copy past error.

**Comment by smartdummies** [comment]
Did my updates get posted to this or do I need to do a new pull request?

**Comment by NathanKell** [comment]
Ah dang, conflicts. Hmm, @pap1723 can you import the identicalpart changes into your xls?

**Comment by pap1723** [comment]
Let me review later. I'll roll the changes in.

**Comment by pap1723** [comment]
The Identical Parts changes have been added for the release. The Entry Cost Modifiers are no longer working the way that they were before. The whole system has been re-written so these ECM's will be applied, but in a completely different way.

**Pull request closed without merging**
