### PR TITLE
Add Avionics to RN Soviet Spacecraft / Salyut / Skylab

### PR DESCRIPTION
**Pull request by Brummi1234**
I added avionics to some RaiderNick parts, including:
Vostok, Voskhod, Soyuz, Zond, Progress, Salyut1-4/6/7, Almaz3-5, Skylab and the VA capsule.

These numbers are mostly made up to go in line with other command pods.

This is my first ever PR so please let me know if i did something wrong.

### CODE REVIEW

**Comment by Brummi1234** [comment]
#876

**Comment by Tidal-Stream** [comment]
To control Salyut you need the Salyut ASAS unit (the part name is salyut_asas). If you add avionics to the station, wouldn't this make the ASAS unit almost useless? Similarly to the way the Saturn IB avionics ring contains the avionics for the stage, I think here the radial ASAS unit should contain the avionics.

**Comment by Bornholio** [comment]
I'd say @Tidal-Stream is correct, take a look if it is operating as intended

**Comment by pap1723** [comment]
@Brummi1234 any update on how this is working?

**Comment by pap1723** [comment]
Moved this to a new branch to finish cleaning up this branch for removal.

https://github.com/KSP-RO/RP-0/tree/brummi-rn-station-avionics

**Pull request closed without merging**
