### PR TITLE
Manned Venus flyby - contract

### PR DESCRIPTION
**Pull request by winged7**

### CODE REVIEW

**Comment by SirKeplan** [comment]
Should this be Crewed, rather than Manned? applies to #350 too.

**Comment by winged7** [comment]
Does it make any difference? (Sorry I'm not native english speaker)

**Comment by NathanKell** [comment]
@SirKeplan is correct here. We very definitely use Crewed / Uncrewed rather than Manned/Unmanned to stay gender-neutral. :)

**Comment by NathanKell** [comment]
Also, I note the description requires a gravity assist, but there's no parameter that actually requires it for completion. Should the description perhaps be altered to suggest, rather than demand, a gravity assist?

**Comment by winged7** [comment]
Updated version with suggestion instead of demand.

**Comment by NathanKell** [comment]
Looks good! Almost there, except please do also make the change from Manned to crewed in the title and filename as well as the description (indeed, any references whatsoever to manned should become crewed, and unmanned to uncrewed).

**Comment by winged7** [comment]
Done :)

**Pull request merged**
