### PR TITLE
new parts

### PR DESCRIPTION
**Pull request by winged7**
- probe parachute from FASA
- MB-3-3 engine from FASA
- spacecraft LM adapter from FASA
- airbrake (stock)
- avionicsnoseCone (stock)
- fuel line (stock)
- electric propeller engine from KAX
- heavy landing gear from KAX
- STAR 17 from KK_ATK pack
- GPHS-RTG from SXT
- GPHS-RTG shielded from SXT

### CODE REVIEW

**Comment by stratochief66** [comment]
Star 17 looks good, as does the FASA LM adapter.

Some of the parts might warrant some discussion about the role we want them to play in RP-0 (ie. the fuel line, I feel like that part could be easily abused. I'm unsure how it could be changed to perform well as an RP-0 part)

Some parts might need a bit of description about form and function since I am unfamiliar with them. For instance, is the KAX landing gear some gear for planes?

Perhaps in your PR notes, if you could describe the part a bit, and what tech era and node you are proposing placing it. It might also be worth stating whether you are proposing initial placement of the part, of if it is being moved from one to another.

I know much of that information can be gleaned from careful analysis of the PR, but if you could put some of it upfront in the PR notes, it would make PRs a lot easier to review, and it would be very much appreciated :)

The other existing parachutes (other than specific craft FASA ones) appear to open on Start. Currently, only heatshields appear in Survivability and the FASA Mini Parachute shows in 'Miniaturization' (I think due to it's non-RP-0 tech placement?) and that might not be a bad place to stick it officially. Thoughts? Should it be in Start, or Survivability, or Miniaturization since it might be the smallest chute? Is there a way for us to differentiate the abilities/limits of various chutes as we can with heat shields?

@NathanKell or someone should look at the plane parts, as I have no basis for thinking where they belong and how they should be judged.

**Comment by NathanKell** [comment]
MB-3-3 is exactly the LR79-NA-13. It should be placed in the same node that unlocks in, and cost (LR79 base cost + CONFIG cost of LR79-NA-13). Its entrycost should be, likewise, the entrycost of the LR79 + entrycost of the LR79-NA-13 CONFIG.

All parachutes should go in Start, IMO.

The fuel line has unlimited flow rate, and thus allows better-than-present-technology crossfeeding. For that reason it should not unlock so early, IMO. On the other hand, now that decouplers can be set to allow crossfeeding from the start, that ship has sailed, so I guess that placement is workable for now.

**Comment by NathanKell** [comment]
Airplane related parts look fine.

**Comment by winged7** [comment]
I've added also GPHS-RTG from SXT.

**Pull request merged**
