### PR TITLE
Add LLV_* engines and decouplers.

### PR DESCRIPTION
**Pull request by ahmedcharles**
I'm interested in suggestions for the costs on the C and D engines, since I don't have a good reference point.

### CODE REVIEW

**Comment by SirKeplan** [comment]
hmm, looks like there is already a bit of a prototypical inconsistency here, the N1 3rd stage used 4 X NK-21s (later upgraded to NK-39s but unflown). this might be worth fixing too.

**Comment by ahmedcharles** [comment]
I was just looking at the configs for the N1 Block A and they all have different values for stuff. Should they be consistent (and perhaps listed in one place)? I know that's not stored in this repo, but in RealismOverhaul.

**Comment by SirKeplan** [comment]
Huh, just looked at them myself, there must have been a great deal of confusion when they where made. some of the numbers are way off or from the wrong engines.

For now i'd say you should leave out the `GameData/RP-0/Tantares_Engines.cfg` file, then as you say some stuff needs doing in the RealismOverhaul repo.

**Comment by ahmedcharles** [comment]
What do you suggest in terms of pricing, or should I just leave that out for now?

**Comment by SirKeplan** [comment]
probably base it on multiples of these this https://github.com/ahmedcharles/RP-0/blob/057bbd066c5094f03f6bee06967a41151077fa07/tree.yml#L1978-L1982 , though these are kinda provisional as just based on the other engines prices.

**Comment by ahmedcharles** [comment]
Done, I think :)

**Pull request merged**
