### PR TITLE
Fix config node unlocks for RN's R-7 engines.

### PR DESCRIPTION
**Pull request by ahmedcharles**
This doesn't work yet, but I'm not sure what else could be going wrong.

### CODE REVIEW

**Comment by ahmedcharles** [comment]
This makes it so that the configs unlock in the correct nodes.

**Comment by ahmedcharles** [comment]
Any feedback on this?

**Comment by NathanKell** [comment]
This...doesn't seem to have anything to do with TF...?

Except to the extent that it looks like those configs are RN-specific, so I wouldn't be surprised if they have no TF configs because they're not using the global configs (where the TF configging is done).

**Comment by ahmedcharles** [comment]
On, I just didn't change the comment.

**Comment by ahmedcharles** [comment]
That's a better commit comment.

**Comment by NathanKell** [comment]
Ah, that makes more sense. I wonder if we now have enough global configs that we can harmonize with raidernick's configs?

**Comment by ahmedcharles** [comment]
All of the RN TF configs map to the stats of an existing TF config, i.e. he didn't create different reliability profiles from the 'global' ones.

However, the engine configs themselves are different, since they lack the thrust of the verniers, since they are separate engines. Granted, this also means that RN's version of the LV is more likely to have a failure, since there are more engines being modeled.

**Comment by ahmedcharles** [comment]
Anyways, any unification would have to be done in RO, not RP-0, so this should be good as is?

**Comment by pap1723** [comment]
This is taken care of with the new RD-107/RD-108 configs

**Pull request closed without merging**
