### PR TITLE
1.2 update

### PR DESCRIPTION
**Pull request by rsparkyc**
I removed a bunch of the electric charge usage code, because 1) I couldn't figure out the new code that would be needed, and 2) I think this may be supported in stock.

I'm sure there's more work to do here, but wanted to at least get something started.

### CODE REVIEW

**Comment by rsparkyc** [comment]
Also created this PR for kerbal renamer (a RP-0 dependency) https://github.com/KSP-RO/KerbalRenamer/pull/2/files

**Comment by leudaimon** [comment]
I believe the changes to make use of the major update of CC must be finished before RP-0 release. I started looking into it with help from @NathanKell at #571 and #573, but didn't get the time to work on this properly. Given I found the stuff for configuring contracts more complicated than I expected, and probably beyond my abilities, if someone is up to take this over, I would be very thankful.

**Comment by rsparkyc** [comment]
Ok, awesome, that gives me some stuff to look into.

**Comment by rsparkyc** [comment]
Ok @leudaimon, those CC updates have been put here: https://github.com/KSP-RO/RP-0/pull/606/commits

**Pull request merged**
