### PR TITLE
Created PARTUPGRADES for the RF Fuel Tank Types

### PR DESCRIPTION
**Pull request by pap1723**
In reference to #523 I decided to create very simple PARTUPGRADES to show up in the Tech Tree for each of the different types of fuel tanks made available by RealFuels.

I have used stock Icons so that they will work on any install and given them no costs to unlock (because they don't actually do anything, they are just informative).

Here they are in action:
http://imgur.com/a/6yfvB

### CODE REVIEW

**Comment by PhineasFreak** [comment]
I imagine that we can replace the stock tank part names with the ones from procedural parts, right? Asking only out of curiosity.

**Comment by pap1723** [comment]
Yes, basically any valid part name will work. In the future, it will be
VERY useful to include the diameter increases for Procedurals as well.

**Comment by PhineasFreak** [comment]
Isn't that possible with the above system? I mean, these are just dummy parts in the tech tree, i imagine that you can add more with different information, right?

**Comment by NathanKell** [comment]
It would be good to get rid of all dummy parts, that's what these are meant
to replace

**Comment by pap1723** [comment]
@PhineasFreak Yes, I am sorry, I wasn't clear in what I meant. This is absolutely the easiest way to show when the Diameter increases will happen in the tech tree. The SSTU parts are currently setup this way.

I will be creating them for the Procedural Parts as well as the Tech Level increases for RCS as well.

**Comment by pap1723** [comment]
OK, in reference to the above, there is this bit of code and I want to make sure I understand what the description / title should be to make sense to the player...

    @RF_TECHLEVELS
    {
        @ENGINETYPE,*:HAS[~name[N]]
        {
            %TLTECH0 = basicRocketry
            %TLTECH1 = generalRocketry
            %TLTECH2 = advRocketry
            %TLTECH3 = heavyRocketry
            %TLTECH4 = heavierRocketry
            %TLTECH5 = veryHeavyRocketry
            %TLTECH6 = experimentalRocketry
            %TLTECH7 = giganticRocketry
        }
        @ENGINETYPE,*:HAS[#name[S*]]
        {
            %TLTECH0 = basicRocketry
            %TLTECH1 = basicSolids
            %TLTECH2 = matureSolids
            %TLTECH3 = advFuelSystems
            %TLTECH4 = largeVolumeContainment
            %TLTECH5 = highPerformanceFuelSystems
            %TLTECH6 = specializedFuelStorage
            %TLTECH7 = exoticFuelStorage
        }
    }

**Comment by NathanKell** [comment]
That sets where each TL for generic engines (RCS, x kN Thruster, proc
solids, etc) unlocks.

The top one is saying all non-nuclear generics, the bottom for solids.

**Comment by leudaimon** [comment]
Given the increase in thrust and Isp will depend on the specific engine and fuel, I guess you can just state that Isp and thrust of RCS (or solids in the second case) were uprated, without further detail.

As we are mentioning things hidden in the tech tree... isn't it possible to show alternate configs of engines (including here the different fuels that get available for RCS) in the tech tree somehow?

**Comment by pap1723** [comment]
The original thing that made me think of this is with the different Engine
Configs that get unlocked, but here is where it gets tricky...

You need to have a part to point to in order to create an icon. As we all
know, almost all of the engines are implemented by mods. Trying to create
the icons required will have to be done at a mod level for each of the
engine configs you want to show. That is the more complicated part of it.

**Comment by NathanKell** [comment]
Nope just have a single generic engine part, perhaps added by RO itself
(someone promised to make us one), make it category -1 and under ORPHANS so
it won't show up, and use that as the config unlock icon

**Comment by pap1723** [comment]
Yep @NathanKell that will work very well.

The only other issue I see with it (don't know how to get around it) is that whether you have a mod installed to include the engine or not, the Engine Config PARTUPGRADE tech unlock will show in the tree.

Is there a way around that? Otherwise, it becomes much more confusing than if we didn't add them.

**Comment by NathanKell** [comment]
Use :NEEDS[] on the part upgrade?

**Comment by pap1723** [comment]
That is what I thought as well with a NEEDS[]

Whoever creates them will just have to find all of the mods that include each engine.

**Comment by NathanKell** [comment]
You might be able to do some magic with external node editing and placing
the patch in the engine global config

**Comment by pap1723** [comment]
I think you meant that YOU (NathanKell) might be able to do that because I only understood some of your words. ;)

**Comment by NathanKell** [comment]
Hehe. I'll see if I can come up with something

On May 24, 2017 1:02 PM, "Pap" <notifications@github.com> wrote:

I think you meant that YOU (NathanKell) might be able to do that because I
only understood some of your words. ;)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/KSP-RO/RP-0/pull/657#issuecomment-303835456>, or mute
the thread

**Comment by NathanKell** [comment]
@sarbian we can write to external things yeah? Idea is in a foo[] {} we
have %root/PARTUPGRADE[bar] {} to create that PARTUPGRADE (using % because
that patch may run many times) and then somewhere else we do
@PARTUPGRADE[bar]:FOR[later pass] and actually fill it in.

Does something like that work?

**Comment by sarbian** [comment]
Yes you can do that. I nearly forgot that I added it...
http://forum.kerbalspaceprogram.com/index.php?/topic/50533-130-module-manager-280-may-26th-2017-better-late-than-never/&do=findComment&comment=2413546

**Comment by pianojosh** [comment]
Comment from the cheap seats: Might this be a good place to describe what the tank types are? I don't think there's any in-game explanation of them.

Cryogenic: "Additional insulation when you need your cryogenic liquids to last days rather than hours. Useful if you need longer than usual coasts for departure stages or Cryogenic Mun/Minmus/Moon insertion and landers. For boosters and most departure stages, stick with Default and add a bit extra of your colder liquid(s), the mass penalty of Cryogenic isn't necessary for them.

ServiceModule: "Highly pressurized and heavily insulated. Use if you need cryogenics to last for more than a few days, such as fuel cell tanks"

Balloon/BallonCryo: "Much lighter than Default/Cryogenic, but at a higher cost. Used by Atlas and Centaur in real life. Rarely used in the real world due to complicated ground handling and structural weakness."

Maybe not necessary, exactly, but as long as all that description room is there, could put it to good use.

**Comment by NathanKell** [comment]
@sarbian thanks, I'll have a poke when I get home.

@pianojosh that's an excellent point! We never do describe them ingame.

**Comment by NathanKell** [comment]
Yep, ok, I think I have a way to do this.

1. in a normal (non-patching) cfg, create the PARTUPGRADE and have a count = 0 line.
2. In the engine global configs, use that linked syntax to increment count in that PARTUPGRADE. That means if the global config is applied once, count will be 1, if twice, count will be 2, etc.
3. Delete all PARTUPGRADEs with count == 0

Presto!

**Comment by NathanKell** [comment]
See https://github.com/KSP-RO/RealismOverhaul/pull/1654

**Pull request merged**
