### PR TITLE
RN&Tantares R7 re-placement

### PR DESCRIPTION
**Pull request by batuhantasli**
Re-placed RN and Tantares R7 tanks as well as RN sputnik fairings etc to the Basic Construction node. Mercury - Atlas LV was already there so it should be ok now with the avionics restriction.

### CODE REVIEW

**Comment by NathanKell** [comment]
Can you also tech-restrict the avionics being assigned?

**Comment by batuhantasli** [comment]
@NathanKell sorry, how do I do that?

**Comment by NathanKell** [comment]
Whoops, missed this.
When you add the avionics module, i.e.
```
@PART[foo]:FOR[RP-0]
{
	MODULE
	{
		name = ModuleAvionics
		massLimit = 5.0
		techRequired = stability // or whatever
	}
}
```

**Comment by NathanKell** [comment]
(the avionics are presumably added in Avionics.cfg -- if the add is for multiple parts, break it out into single patches, one per part, so you can set individual tech requireds)

**Pull request merged**
