### PR TITLE
Move ALL AJ10-Mids to 1960

### PR DESCRIPTION
**Pull request by lpgagnon**
follow-up to https://github.com/KSP-RO/RP-0/pull/1116
which only handled the ROE- variants

### CODE REVIEW

**Comment by DRVeyl** [comment]
Why did you clear the solids entry costs?

**Comment by lpgagnon** [comment]
I didn't. _someone_ apparently forgot to regen .cfgs after updating .jsons.

**Comment by Capkirk123** [comment]
Oops

**Comment by lpgagnon** [comment]
That would be because _somebody_ didn't actually test his changes. Year was changed but not the actual node, which is the thing that matters. Will fix.

**Comment by lpgagnon** [comment]
clearly everything is correct and no testing is needed:

Screen Shot 2021-03-30 at 09 59 37

**Comment by lpgagnon** [comment]
fixed, and actually confirmed the SXT version shows up in the right node

**Pull request merged**
