### PR TITLE
Add Libra_Engine_A.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by SirKeplan** [comment]
There isn't a Libra_Engine_C or D?

**Comment by ahmedcharles** [comment]
There are only two stages in Tantares LV for the Libra. Why is that surprising?

**Comment by SirKeplan** [comment]
because you talked about costs for the C and D engines.

**Comment by ahmedcharles** [comment]
Yeah, it's an issue where github/my browser puts messages from previous PR's into future PR's... it's annoying.

**Comment by SirKeplan** [comment]
OK, seems the Tantares part is effectively an integrated RD-858 and RD-859, so this should be double the price.

**Comment by ahmedcharles** [comment]
Updated

**Pull request merged**
