### PR TITLE
Manned Mars flyby - contract

### PR DESCRIPTION
**Pull request by winged7**

### CODE REVIEW

**Comment by NathanKell** [comment]
Same two comments as the Venus contract #351

**Comment by winged7** [comment]
Updated version with suggestion to use gravity assist.

**Comment by NathanKell** [comment]
Looks good! Almost there, except please do also make the change from Manned to crewed in the title and filename as well as the description (indeed, any references whatsoever to manned should become crewed, and unmanned to uncrewed).

**Comment by winged7** [comment]
Updated.

**Pull request merged**
