### PR TITLE
Assorted part fixes from my train journey.

### PR DESCRIPTION
**Pull request by pjf**
See individual commit messages for details.

### CODE REVIEW

**Comment by NathanKell** [comment]
@pjf proceduralConeLiquid is a non-RF part that is hidden when RF is present. However, no Proc Parts has been released with that fix so it's in git only. I suggest not placing it, though, since it's not a supported part--though if placed, as with other parts, it should have cost 0.1.

Other than that, awesome! :)

**Comment by pjf** [comment]
D'oh, how did my notes file get in here? :/

proceduralConeLiquid was already placed, I just popped a price on it. But let me fix that now.

**Comment by pjf** [comment]
Amended. :)

**Comment by NathanKell** [comment]
Sorry, didn't notice this earlier. The procedural wings, like other procedural parts, should have a cost of 0.1. Also we should probably make a FIXME or TODO note about giving wings and control surfaces the same price as a procedural one *of the same size*, not just "tenbux for all!" :)

**Comment by pjf** [comment]
> The procedural wings, like other procedural parts, should have a cost of 0.1.

That's cool. This PR doesn't change the cost of any pWings.

> Also we should probably make a FIXME or TODO note about giving wings and control surfaces the same price as a procedural one of the same size, not just "tenbux for all!"

Done. This is now ticket #107.

Is there anything else blocking this from being merged? ;)

**Comment by NathanKell** [comment]
The issues are:
B9_Aero_Wing_Procedural_TypeA: *stdwing
B9_Aero_Wing_Procedural_TypeB: *stdwing
B9_Aero_Wing_Procedural_TypeC: *stdwing

Although it looks like that's from one of your prior commits? Beyond that, no, looks fine to me. :) Sorry for the delay.

**Comment by pjf** [comment]
Hooray! :) Merging.

**Pull request merged**
