### PR TITLE
Gemini white

### PR DESCRIPTION
**Pull request by winged7**

### CODE REVIEW

**Comment by stratochief66** [comment]
@NathanKell setup the Gemini White to be a bit more powerful than the standard part, should it be made more pricey NathanKell?

**Comment by NathanKell** [comment]
Ya, see #239 which also works on this for more details?

**Comment by winged7** [comment]
So Gemini White is more powerful? I can make it more pricey if you want.

**Comment by winged7** [comment]
316k for entryCost and 6k for unit cost. exactly the same as what federicoaa proposed.
https://github.com/KSP-RO/RP-0/pull/239/files

**Comment by NathanKell** [comment]
The entry cost modifiers need to also be made, since I presume it wouldn't be right to research this then have to pay full price for Gemini, and vice versa.

**Comment by winged7** [comment]
entryCostModifiers for Gemini: https://github.com/KSP-RO/RP-0/pull/352

**Comment by NathanKell** [comment]
Closes #239

**Pull request merged**
