### PR TITLE
Support for FRE LE-7

### PR DESCRIPTION
**Pull request by Zarbizaure**
The LE-7 engine is almost ready and will come with the latest FRE update, probably later today.
I will also include pricing by config.

### CODE REVIEW

**Comment by Zarbizaure** [comment]
And...is my pricing for the LE-5 incoherent? Here I see that people placed LE-7 at 1900 funds...and my LE-5 cost 3500. What's wrong?

**Comment by NathanKell** [comment]
When adding the second copy of an engine, please use *name to make the first one an anchor, and just reference it by &name in the second. I.e.

cryoengine-25-1: *LE7
cost: ...
entryCost...

FRELE7: &LE7

As to the pricing, I'm afraid I have no idea as to the cost of either, except what I saw on nautix regarding the LE-5's stage.  @winged7 what did you base that cost on? (I think that was your commit?)

**Comment by Zarbizaure** [comment]
Oh yes I saw that. I will correct it soon.
Maybe the LE-7 is underpriced? Or the LE-5 is overpriced, but we need LE-7>LE-5.

**Comment by Zarbizaure** [comment]
$30M for LE-5 stage http://astronautix.com/stages/le5.htm
$80M for LE-7 stage http://astronautix.com/stages/h21.htm (one engine)
So the LE-7 is about thrice the LE-5 price. How could we fix that?
Let's assume:

- LE-5 price: $15M by currency convertor: $3500k 1965 USD so **3500 funds**

- LE-7 price: $40M by currency convertor: $10000k 1965 USD so **10000 funds**
But these prices are way too high compared to other engines in KSP (example: Vulcain costs 6400 funds and is a bit more powerful than the LE-7; RL-10 (a bit similar to LE-5) also costs way less (1300 funds). I know there could be a difference depending on the tehcnology used (gas-cycle,...) but it doesnt explain a 2-3x factor.

**Comment by NathanKell** [comment]
You'd want to compare with the period-specific RL10, which would cost quite a bit more (check the CONFIG additional costs). But yeah, I think probably what it comes down to is different costing for Japanese use, and also flight rate. As http://www.astronautix.com/articles/costhing.htm points out, in some ways this endeavor is a fool's errand. :]

I would therefore suggest going with 1/3 of the stage cost instead of 1/2. That places the LE-5 at about the same price/effectiveness point as the RL10A-4, and the LE-7 at about the same point as Vulcain.

**Comment by Zarbizaure** [comment]
So about **6210 funds** for the LE-7 and **2650 funds** for the LE-5. This seems better than the previous prices.
Also, I know that price for an engine means absolutely nothing; as you said it really depends on the production number, which could explain why the RL-10 is much cheaper.

Should I change the price for all LE-7 in RO? If so you could accept my PR.

**Comment by Zarbizaure** [comment]
apparently Travis failed, I will let you fix that.
Also thinking on my next engine I thought RO should really integrate next-gen avionics, like this one: https://rocketlabusa.com/about-us/electronic-systems/avionics/
This will reduce rocket's weight by a lot and therefore increase payload capacity. This avionic module is indeed on a small rocket, but it's a bit painfull to be stuck with the early and heavy saturn avionic in RO since there are much more performant ones...

**Comment by Temeter** [comment]
I've encountered the same issue when updating SSTU tech tree. It's important to set the anchor first, and you got no references above. Seems like Nathan confused symbols, should be this way:

> cryoengine-25-1: &LE7
> cost: ...
> entryCost...
> 
> FRELE7: *LE7

Which is funny cause Nate was the one explaining that stuff to me. :D

**Comment by Zarbizaure** [comment]
thanks @Temeter ! it should be fine now ;)

**Pull request merged**
