### PR TITLE
Habitat Pack

### PR DESCRIPTION
**Pull request by winged7**

### CODE REVIEW

**Comment by NathanKell** [comment]
Are these priced off Bigelow's numbers?

**Comment by winged7** [comment]
You mean "Is the price based on Bigelow's numbers?" No, it's total guess ;) 

I can delete numbers if you want.

**Comment by SirKeplan** [comment]
cost of a BA330 looks to be around $125M in modern dollars

https://books.google.co.uk/books?id=9qigBAAAQBAJ&pg=PA135&lpg=PA135&dq=bigelow+330+cost&source=bl&ots=5A3ROXqwAr&sig=5bHxdsXDERnaezB04KNGLJTfmIg&hl=en&sa=X&ved=0CFcQ6AEwCGoVChMIwLrnqb6zyAIVhb8UCh2LYANa#v=onepage&q=bigelow%20330%20cost&f=false

**Comment by winged7** [comment]
125mln USD - BA330
500mln USD - BA 2100
http://www.rocketstem.org/2014/03/12/city-in-the-sky-building-a-cheaper-space-station-with-bigelow-modules/

83-143mln USD - ISS Centrifuge demo (let's assume 113mln)
https://en.wikipedia.org/wiki/Nautilus-X (at the bottom of the page)

3700 mln USD development cost for the Nautilus X Centrifuge but it seems like pretty optimistic number (much cheaper than Orion)
http://phys.org/news/2011-02-nasa-nautilus-x-reusable-deep-spacecraft.html

**Pull request merged**
