### PR TITLE
Mk3 system - pricing

### PR DESCRIPTION
**Pull request by winged7**
https://github.com/KSP-RO/RP-0/issues/237

### CODE REVIEW

**Comment by NathanKell** [comment]
Pending input on #237

**Comment by winged7** [comment]
Not sure what I need to do here.

**Comment by winged7** [comment]
So for example: Mk3 Cockpit should be cheaper to unlock than I unlock Mk2 Cockpit first? How much cheaper?

**Comment by NathanKell** [comment]
I'd say maybe 1/3 the cost of the cockpit should be the shielding system in each case.

**Comment by winged7** [comment]
something like that?

@PART,*:HAS[#tag[heatshieldedLEO]]
	{
		maxSubtraction = 16000
		entryCostSubtractors
		{
			0625-Heatshield = 16000
			Heatshield-1M = 16000
			1-25-Heatshield = 16000
			mk1pod = 16000
			FASAMercuryPod = 16000
			rn-vostok-sc = 16000
			FASAGeminiPod2 = 16000
			rn_voskhod_sc = 16000
			mk2CrewCabin = 16000
			mk2Cockpit_Standard = 16000
			mk2Cockpit_Inline = 16000
			mk3Cockpit_Shuttle = 16000
			mk3CrewCabin = 16000
			B9_Cockpit_MK2 = 16000
			B9_Cockpit_S3 = 16000
			B9_Cockpit_S2 = 16000
			B9_Cockpit_MK5 = 16000
			B9_Cockpit_M27 = 16000
			HL_Aero_Cockpit = 16000	
			B9_Cockpit_S2_Body_Crew_6m = 16000
			B9_Cockpit_S2_Body_Crew = 16000
			B9_Cockpit_MK2_Body_Crew_2m = 16000
		}
	}

but with much bigger number for mk3cockpit right? 1/3 of the develompment cost =  173300

**Comment by NathanKell** [comment]
Yep, where you want to tag with say Mk3Heatshield and then have a subtractor (and max subtractor) of, say, 1/3 the cockpit price (which would probably be 4/5 of a fuel tank price and 2/3 of a cargo bay price?)

Uh...to be clear _not_ just adding the new parts to that old tag. The point is that there should be one of these set up for each "type" of shielding -- LEO ablative, lunar ablative, X-15, DynaSoar/Mk1, Mk2/S2, Mk3/S3/etc.

**Comment by winged7** [comment]
Sorry but I'm giving up here. The whole concept of entryCostModifiers is not so very clear to me.

**Comment by NathanKell** [comment]
Ok. Let me write a quick wiki entry on them, and see if that's better. If not, then yeah just leave them unpriced.

**Comment by NathanKell** [comment]
Does this help?
https://github.com/KSP-RO/RP-0/wiki/Entry-Cost-Modifiers

**Comment by winged7** [comment]
Examples in your tutorial are very easy to understand but I still don't know waht exactly I need to do.

https://github.com/KSP-RO/RP-0/pull/353

**Comment by NathanKell** [comment]
Yep, exaclty!
Though per the note on #353 the entry costs probably need to come up--I'd expect something like 20000 for the shielding component of the Mk1, 40 to 50000 for the Mk2/S2, and maybe 100000 or more for the Mk3/S3 (STS is _expensive_).
(so, say, the Mk2 cockpit would be something like 100000 entryCost, with 40-50 of that being the shielding.)

**Comment by winged7** [comment]
but the 4333 is not 1/3 x development cost, this is 1/3 x unit cost.

1/3 of  develompment cost for the mk2 standard cockpit  = 43333 (exactly like you want: between 40 and 50k)

**Comment by NathanKell** [comment]
Ah, I thought the entryCostSubtractor you wrote was 4333. I missed a 3? Oops. :D

**Comment by winged7** [comment]
I switched from 1/3 of the unit cost (4333) to 1/3 of the development cost (43333 - 10x bigger) however 130k for development cost is still a bit cheap compared to Mercury so maybe multiply increase it 2x to 260k?

**Comment by winged7** [comment]
I can delete mk2, mk3, S2, S3 etc. development cost value from tech tree so it will be 20x more expensive than unit cost by default and thus 2x more expensive than now.

**Comment by NathanKell** [comment]
Moving discussion to #237 til we get this figured out. :)

**Pull request merged**
