### PR TITLE
Fix Waypoint Parameters in Contracts

### PR DESCRIPTION
**Pull request by Teykn**
Addresses KSP-RO/ProgramsIssueTracker#107 & other contracts that use WayPoint Parameters.

### CODE REVIEW

**Comment by siimav** [comment]
Hah, even most of the rover contracts in mainline RP-1 have the same issue.

**Comment by siimav** [comment]
And as expected thse errors have carried over to PLC as well. Might as well fix them all at once?

**Comment by Teykn** [comment]
I'll fix the other contracts in PLC that involve Waypoints. Master branch will need a separate PR.

**Comment by Teykn** [comment]
This should cover all the contracts in PLC that had issues with waypoints. Lunar rover, both uncrewed and crewed, didn't have any issues, so left unchanged.

**Pull request merged**
