### PR TITLE
Declare dependency on RealFuels

### PR DESCRIPTION
**Pull request by yump**
This fixes issue #1097.

### CODE REVIEW

**Comment by siimav** [comment]
I think it would be better to require RF version 12.7 or 12.7.4. Anything lower than that wouldn't work anyway.

**Comment by yump** [comment]
TBH I stumbled on this solution while trying to get it to build to start troubleshooting the problem.  Both ModularFlightIntegrator and RealFuels were in the references, but only MFI was listed here.  I copied and pasted on a hunch, and the log errors and breakage went away.

Further investigation reveals that even though MFI is currently on version 1.2.6, it claims to be 1.0.0 through this mechanism.  So that was apparently a deliberate choice of arguments rather than just a maximally accepting default or boilerplate.

**Comment by siimav** [comment]
https://github.com/sarbian/ModularFlightIntegrator/blob/master/Properties/AssemblyInfo.cs#L39
MFI doesn't change either the AssemblyVersion or KSPAssembly numbers on releases to prevent updates from breaking dependant mods.

**Comment by yump** [comment]
Ah, I should mention that this change requires a recompile to be effective, and I didn't include the rebuilt .dll in the PR for the obvious security and, "had to tweak the .csproj to make it build and can't test on Windows," reasons.

**Pull request merged**
