### PR TITLE
Add configs for SpX Dragon 1, 2 and XL

### PR DESCRIPTION
**Pull request by StonesmileGit**
This is a split of a previous PR to only include Dragon 1, 2 and XL, see [here](https://github.com/KSP-RO/RP-0/pull/1392)

### CODE REVIEW

**Comment by siimav** [comment]
Depends on https://github.com/KSP-RO/ROCapsules/pull/82 and https://github.com/KSP-RO/ROCapsules/pull/83

**Comment by siimav** [comment]
All the changes in TREE-Parts.cfg are invalid now that #1459 is merged

**Comment by StonesmileGit** [comment]
Will recompile the configs once the ROC PR's are merged, to avoid doing it more times than needed

**Comment by Capkirk123** [comment]
Considering https://github.com/KSP-RO/ROCapsules/pull/82 and https://github.com/KSP-RO/ROCapsules/pull/83 have been closed, is this PR no longer needed? Should someone else attempt to configure Dragon?

**Comment by StonesmileGit** [comment]
Yeah, seems like there has been very little movement on new RO configs. I'll close this but keep the branch on my repo, for future reference if something happens

**Pull request closed without merging**
