### PR TITLE
Remove TestLite from loading screen tips

### PR DESCRIPTION
**Pull request by Test-Account-KSP**

### CODE REVIEW

**Comment by siimav** [comment]
I wonder if @ec429 has anything to say about it 🤔

**Comment by ec429** [comment]
Is there any specific reason to un-recommend TestLite?  Any missing feature that's now essential for RP-1?  Have to admit I haven't been keeping up with the discourse lately, so maybe I missed something.

**Comment by siimav** [comment]
I think you haven't officially released the missing features that you were working on not too long ago?

**Comment by Test-Account-KSP** [comment]
It's not in the express install so I thought it's unsupported. If it's still supported I will close the PR.

**Comment by ec429** [comment]
@siimav yeah I'm terrible about that.  Wanted to test it all before releasing but didn't have time to play much so there might be some lurking badness.  I've cut a release anyway because I'm not likely to have much KSP-ing time in the _next_ few months either.

**Comment by siimav** [comment]
In that case I'm fine with the loading screen tip staying since the people preferring TL can now manually switch over if they'd like.

**Comment by jwvanderbeck** [comment]
" yeah I'm terrible about that."
Aren't we all?

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by NovemberOrWhatever** [comment]
I'll also note that the Programs and Launch Complexes branch has some heavily rewritten, cleaned up, and better organized loading screen tips. We could just not deal with this until PLC releases, or try to backport some of the tip changes. More an additional note than a suggestion though.

**Pull request closed without merging**
