### PR TITLE
ROE new parts

### PR DESCRIPTION
**Pull request by Capkirk123**
Add tech nodes and ECMs for the new parts added in ROEngines. Also correct the cost of various SRMs that I found to be incorrect during my research for the new ROE parts.

ROEngines PR: https://github.com/KSP-RO/ROEngines/pull/60

### CODE REVIEW

**Comment by lpgagnon** [comment]
Again looking only at the xlr11: ECMs look right, but part costs seem off. ROE version costs 150, Taerobee version costs 250.

**Comment by Capkirk123** [comment]
Price corrected

**Comment by lpgagnon** [comment]
ROE-LR87_LH2V has techRequired=unlockParts

**Comment by Capkirk123** [comment]
TechRequired should be correct on all parts

**Comment by lpgagnon** [comment]
ROE-LR87_LH2V is still getting unlockParts. This part name isn't actually showing up anywhere in this PR

To be clear, I'm not referring to engine configs, but to the new part introduced in https://github.com/KSP-RO/ROEngines/blob/83612d6192f6ee2024489bf0a7bd4ec51857db12/GameData/ROEngines/PartConfigs/LR87_LH2V_BDB.cfg

**Comment by Capkirk123** [comment]
Yelled at parts browser some, TechRequired should definitely be correct on all parts

**Pull request merged**
