### PR TITLE
Add Large Regolith Harvester (kerbalism-large-drill)

### PR DESCRIPTION
**Pull request by Falki-git**
Larger variant of the Regolith Harvester (kerbalism-drill)

### CODE REVIEW

**Comment by lpgagnon** [comment]
Something seems off with the entry costs: with neither drill unlocked, I see the big drill costing 7000 and the small drill 8000. 

Working fine aside from that.

**Comment by Falki-git** [comment]
@lpgagnon , should be good now. Spent a better part of the day trying to figure out how entry cost modifiers work. Base cost of the drill (small one) is 8000. Additional for a large one is 6000, total 14000.

**Comment by siimav** [comment]
Is the new part from base Kerbalism or did it get recently added to ROKerbalism?

**Comment by lpgagnon** [comment]
https://github.com/Standecco/ROKerbalism/pull/78

**Pull request merged**
