### PR TITLE
More lunar/station contracts

### PR DESCRIPTION
**Pull request by Zarbizaure**
Don't know if it's needed but it will add a bit of variety to the game.
Also, I think we need a greater variety of manned contract - perhaps lunar orbital station, lunar village (like the ESA one), rover mission (manned and unmanned: like the Apollo rover or the Mars rovers) or Mars orbital station? This would be cool for a RP-0 end game! So I'll see what I can add based on others contracts pack, but we might be limited by .dll or so (example: how to check how many kilometers a rover travelled on the ground?).

There's apparently already a [rover mission pack](http://spacedock.info/mod/52/Contract%20Pack:%20Rover%20Missions), but it wouldn't be really nice to steal all of its work. Otherwise it seems good, but it needs to be adapted a bit for RP-0.

### CODE REVIEW

**Comment by Zarbizaure** [comment]
Also, why don't all of the RP-0 contracts give science rewards? I think some mission like uncrewed lander, station research or fly-by should give a bit of science. Is there a reason for this?

About the typo: is the (@/Multiplier) correct? Why do we need a slash?

**Comment by Zarbizaure** [comment]
just to say: these contracts are UNTESTED now. I'll do a bit of testing probably tomorrow, but I will be off for a week then. If somebody could test these, it would be really cool. Thanks!

**Comment by Zarbizaure** [comment]
Some changes to move everything related to station/base under HumanHabitationContracts.

**Comment by Zarbizaure** [comment]
okay so it should be almost fine for Spation/Hotel/LunarOutpost contracts. I'll just add a resupply mission to the Lunar Base.

Sorry for the huge amount of commits, I'm not really organized :P

**Comment by Zarbizaure** [comment]
All these commits just added a NewVessel parameter; that way the contract won't be instantly completed if there's already the designed module (crew, science or resupply).

**Comment by NathanKell** [comment]
Wow, awesome! Been a busy few days at work so haven't gotten through yet, but just wanted to register my :+1:

**Comment by Zarbizaure** [comment]
so i'm finally back home! I'll have to test this a bit to check if it works; if someone want to test it, feel free to do it.

**Comment by NathanKell** [comment]
Awesome! Let me know how it goes!

I am going to try to get back to actually dealing with stuff :]

**Comment by Zarbizaure** [comment]
so, sorry if I did not talk a lot about this; I'm on vacation for 15 days. I won't have time to test them soon (I just saw that strangely, some resupply/lunar base expansion contracts were proposed despite there wasn't any lunar Base so I added some requirements) but I didn't played the contracts.

**Comment by stratochief66** [comment]
@Zarbizaure you still around? Sorry we left this so long.

**Pull request closed without merging**
