### PR TITLE
Fix dirty enumerator issue

### PR DESCRIPTION
**Pull request by dgeastman**

### CODE REVIEW

**Comment by NathanKell** [comment]
I am deeply confused by the purpose of this PR--you're replacing a stack-alloc struct enumerator with a heap-alloc list?

**Comment by dgeastman** [comment]
For some reason the enumeration was getting modified during this process so it would throw an error and you wouldn't be able to modify an LC. So this pulls a static list of the keys so any modification becomes irrelevant.

**Comment by NathanKell** [comment]
Sounds like the case where this is true the source and dest dict pointers are identical, so seems better to test for that.

**Comment by NathanKell** [comment]
Unrelated to the actual bug, per discord.

**Pull request closed without merging**
