### PR TITLE
Made waypoint naming for the lunar rover contract consistent

### PR DESCRIPTION
**Pull request by gazpachian**
In certain config points the second waypoint was labeled 'Beta', in others 'Bravo'. Now it's all NATO compliant. _Loud cheering in the background_

### CODE REVIEW

**Comment by siimav** [comment]
This isn't the only contract that has waypoints

**Comment by gazpachian** [comment]
@siimav I went and replaced the occurrences in the other rover contracts as well, as far as I know the rover contracts are the only ones with the aforementioned naming convention in place(?). Please let me know if I missed any!

**Comment by siimav** [comment]
I wonder if this change is going to break  any active rover contracts in existing careers...

**Comment by gazpachian** [comment]
That's a valid concern, but from my understanding (and someone please correct me if I'm wrong) this change does not affect active contracts, only the generation of new contracts. Accepted contracts are stored in a node in the sfs save file together with all relevant data such as waypoint names as they were when you accepted the contract. Someone more experienced with CC specifics can confirm or deny this.

**Pull request merged**
