### PR TITLE
ContractConfigurator contracts

### PR DESCRIPTION
**Pull request by Shurikeeen**
Adds bunch of contracts for RSS. Some descriptions and completion messages are still missing and the rewards are not balanced. You need to install Contract Configurator to use these.

### CODE REVIEW

**Comment by aw1621107** [comment]
>___<

**Comment by NathanKell** [comment]
Thanks so much!

Does Contract Configurator require that all contracts be under that path? If not, I think it would make more sense to have a Contracts folder in the RP-0 folder, and have them in that...?

**Comment by Shurikeeen** [comment]
I have no idea do they need to be in the Contracts folder. You might want to ask that in the Contract Configurator thread.

**Comment by NathanKell** [comment]
@Shurikeeen  Yep, they can be under RP-0. Can you move them there, so the path is GameData/RP-0/Contracts/contractname.cfg ? If you want to group contracts, that's fine too, like Contracts/HSF/various human spaceflight contracts

@jrossignol I haven't missed anything have I?

**Comment by Shurikeeen** [comment]
By the way, I also included a config what gets rid of the stock contracts.

**Comment by jrossignol** [comment]
Overall looks good, a few comments from looking over it:
 * Can you create a [CONTRACT_GROUP](https://github.com/jrossignol/ContractConfigurator/wiki/Contract-Group) and add your contracts to it?  Aside from keeping things nice and organized in the debug menu, there's a few additional features that it allows (limiting the number of active contracts within a group, Contract Configurator min version if you're dependent on a certain feature that gets added), as well as some planned enhacements (player ability to enable/disable contract groups on a per-save basis).
 * Can you remove GameData/RP-0/Contracts/SampleContract.cfg or make sure that it doesn't get packed in your release to the player?  It'll throw an error in the logs because of the invalid values.
 * Any chance you can add indentation to the contracts?  Functionally it makes no difference, but it makes them easier to read and helps prevent some issues such as missed braces (which the KSP parser won't throw an error for, and will occasionally do weird things like put things at the wrong level).
 * You have a couple of text fields that are still TBD :wink:

**Comment by Shurikeeen** [comment]
@jrossignol When I try to make a contract group, I get the error "unexpected child node "CONTRACT_GROUP" found, ignored". I couldn't be bothered to debug it last night.
I did remove the sample contract, it was there mostly if someone wants to add more contracts with the style I used.
If someone who knows how to grammar and wants to fix my writings, go for it. English isn't one of my strongest skills, really. Also, I would appreciate if someone could write more creative descriptions for these contracts.

**Comment by jrossignol** [comment]
CONTRACT_GROUP shouldn't be under CONTRACT_TYPE - it should be its own root node.  You then reference it in CONTRACT_TYPE by name via the contractGroup attribute.

**Comment by Shurikeeen** [comment]
@jrossignol Ah, I see now. Cheers!

**Comment by NathanKell** [comment]
@Shurikeeen  you still working on this branch or should I merge? :)

**Comment by Shurikeeen** [comment]
@NathanKell I have not done too extensive testing on the space station contracts. They might contain bees.

**Comment by Shurikeeen** [comment]
I couldn't figure out how to make the docking parameter work on the station contracts. Maybe ill add them later. You might as well merge this. I'm going to add contracts for all planets later.

**Comment by Shurikeeen** [comment]
42 contracts currently :) There is at least a fly-by contract for every planet as of now.

**Comment by NathanKell** [comment]
Awesome!
And I updated the plugin so it should be safe to run on 1.0, although the tree still needs touchup.

**Comment by Shurikeeen** [comment]
Note that the contract rewards need to be balanced to the new RP-0 tech tree :P

**Comment by NathanKell** [comment]
Noted!

**Pull request merged**
