### PR TITLE
Add missing Crew Training for RO parts

### PR DESCRIPTION
**Pull request by arrowmaster**
Dynasoar Cabin in ProtoSpaceplane to go with the Dyanasoar Cockpit
Apollo D2 Mission Modules to ApolloD2 with the Decent Module
ROC and SXT Apollo LEMs to ApolloLEM

### CODE REVIEW

**Comment by siimav** [comment]
The others look fine but I'm guessing the discussion (and lack of conclusion) in #1506 applies to `ROC-DynaCabinMoroz` as well.

**Comment by arrowmaster** [comment]
I agree with the discussion in #1506 that its not ideal. But the Big Gemini Crew Module is already included because it is expected to be used with Gemini. https://github.com/KSP-RO/RP-0/pull/1636/commits/c9d41116b28dfd1a5c8b778f1aa913866b8d0037#diff-471695849b93f49cb30d9021abc02cd0f3a87dac2fb836081c68bc6d0449aa48R103

**Comment by NathanKell** [comment]
I think the compromise from #1506 is fine here as well--a nominal (two month? Reduced to less than that with AC upgrades obvs) proficiency training, and then a reasonable (i.e. 2/3 of the cockpit?) mission training.

**Comment by arrowmaster** [comment]
I removed the Dynasoar crew cabin from the PR as I do not have the time currently to learn about making the requested changes.

**Pull request merged**
